services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    LaxCorp\ApiBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Helper/DoctrineMatcherResult.php}'
